[package]
name = "stn_http_proxy_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features=[] }
httparse = { version = "1.4", features=[] }
futures = "0.3"
